// Tunables. Everything you'd want to tweak lives here.
export const MSG_TTL_S = 30;          // ephemeral: seconds a message lives
export const MSG_DECAY_START = 0.6;   // fraction of TTL after which a message starts dimming to death
export const DECAY_WAVE = 0.5;        // share of the dying time the right-to-left wave takes to reach the first letter
export const MSG_MAX = 100;           // chars per message
export const MSG_PER_MIN = 10;        // own messages per sliding minute, same as relay.js; extra ones crumble
export const TYPE_CPS = 25;           // appear: incoming messages type in at this many chars/s
export const DOT_TTL_FRAC = 0.04;     // disappear: a dropping letter shows as '.' for this fraction of TTL
export const SEND_MS = 600;           // send: your message rises from the cursor over this time
export const SEND_ROWS = 2;           // ...and settles this many rows above it
export const BAD_TTL_S = 1.5;         // a message with curse words shakes, then crumbles over this time
export const BAD_CRUMBLE_START = 0.6; // fraction of BAD_TTL_S after which its letters start dropping out
export const BAD_SHAKE_MS = 500;
export const NUDGE_ROWS = 4;           // overlapping messages shift up/down up to this many rows
export const PAGE_STEP = 0.5;           // PageUp/PageDown/Home/End move this fraction of the screen
export const ARROW_STEP_CHARS = 2;    // arrows move the cursor this many chars per press
export const CURSOR_MARGIN = [12, 4];   // cols, rows the arrow-moved cursor keeps from the screen edge
export const ARROW_FAST = 5;          // Ctrl+arrow multiplies the step
export const INTRO_QUIET_S = 3;       // no incoming messages for this long after load (title)...
export const INTRO_RAMP_S = 8;        // ...then they ramp up to the full rate over this time
export const MSG_JITTER_S = 2;        // incoming messages start typing after a random delay up to this
export const WS_URL = location.hostname === 'localhost' ? 'ws://localhost:7805'  // relay.js
  : 'wss://fit-companion-arbitration-facts.trycloudflare.com';  // quick tunnel, changes on restart
export const POS_SEND_MS = 2000;      // your pin position goes to the relay at most this often (relay: POS_GAP_MS 1000)
export const PLAYER_MARK = ['x', 13];  // char, color (light magenta): where other players have their pin
export const WS_IDLE_S = 60;          // no input for this long closes the socket; next input reconnects
export const AUTO_SPIN = 0.04;        // rad/s when idle
export const IDLE_RESUME_S = 8;       // resume spin after this idle time
export const ZOOM_START = 0.85;       // globe radius as fraction of screen half-height
export const ZOOM_MIN = 0.35;
export const ZOOM_MAX_X = 10;          // max zoom, as shown in the status bar
export const ZOOM_WHEEL = 0.0015;
export const ZOOM_KEY = 1.25;          // +/- zoom factor per press (only while not typing)
export const RENDER_FPS = 30;
export const CURSOR_BLINK_MS = 500;
export const CURSOR_CHAR = '\u2588';     // full block
export const CURSOR_COLOR = 15;           // white
// day/night from the real UTC sun; d = cos of sun angle at a point
export const DAY_MIN = 0.35;             // brightness right after sunrise (day side: DAY_MIN..1)
export const TWILIGHT = 0.035;           // |d| below this is the terminator band
export const TWILIGHT_LAND = ['.', 6];   // char, color (brown)
export const TWILIGHT_OCEAN = ['.', 1];  // dark blue
export const NIGHT_LAND = ['.', 8];      // char, color
export const NIGHT_OCEAN = [' ', 0];
export const LIGHT_RADIUS_DEG = 0.8;     // city glow radius per size step (cities are size 1-3)
export const TOWN_DENSITY = 0.004;       // chance a dark night cell gets a small fake town light
export const NIGHT_LIGHTS = [[0.6, '*', 14], [0.3, '+', 14], [0.1, '.', 6]];  // [min brightness, char, color]
export const LAND_RAMP = '.,:;=+';         // light, similar-shaped glyphs keep the planet soft
export const OCEAN_RAMP = ' .,:';
export const COAST_CHAR = '.';            // ocean cells with a bit of land
export const ICE_LAT = 1.15;              // rad; land beyond this is ice
// EGA palette indices (see style.css): dark -> lit
export const LAND_COLORS = [2, 2, 10];    // green, green, light green
export const ICE_COLORS = [8, 7, 15];     // dark gray, light gray, white
export const OCEAN_COLORS = [1, 1, 9];    // blue, blue, light blue
export const STAR_COLOR = 8;
export const MSG_FADE = [[0.4, 15], [0.8, 7], [Infinity, 8]];  // [max distance from you (1 = screen edge), color]: white, gray, dark gray
export const SHADOW_DIM = { 15: 7, 7: 8, 8: 0, 10: 2, 2: 8, 9: 1, 1: 0, 11: 3, 3: 8, 14: 6, 6: 8, 12: 4, 4: 8, 13: 5, 5: 8 };  // EGA color -> one step dimmer, for the ring around messages
export const CLUSTER = [16, 2];           // cols, rows: messages this close to a group's first one join its stack
export const STACK_MAX = 5;               // newest messages a stack shows, oldest on top
export const EDGE_COLOR = 7;             // others' messages on the far side or off screen, pinned to the nearest edge (light gray)
export const EDGE_RIM = 0.97;            // far-side messages sit at this fraction of the globe radius
export const ME_COLOR = 14;               // yellow
export const BAD_COLOR = 12;              // light red: filtered message
export const STAR_COUNT = 1500;          // fixed stars on the sky sphere
export const SUN_RADIUS = 1.5;           // in char widths
export const SUN_GLOW = 5;               // glow radius, char widths
export const SUN_RAY = 9;                // ray length, char widths
export const SUN_RAYS = 8;
// lens flare ghosts along the line sun -> screen center -> beyond: [position (0 = sun, 1 = center), text, color]
export const FLARE = [[0.35, 'o', 14], [0.6, '.', 6], [1.15, '()', 11], [1.45, 'o', 13], [1.9, '( )', 9], [2.3, '.', 11]];
export const MOON_FROM_ANTISUN = 0.5;   // rad the moon sits away from the point opposite the sun
export const MOON_RADIUS = 2.5;          // char widths
export const MOON_HIT = 1.5;            // clicks this many char widths past the moon's radius still land on it
export const MOON_SHADE = [[0.5, '@', 15], [0.15, 'o', 7], [-1, '.', 8]];  // [min sun-facing, char, color]; shows the phase
export const STAR_FOV = 1.2;             // rad; how wide the sky looks across the screen width
export const TITLE_TEXT = 'ASCII PLANET';
export const TITLE_SUB = 'Alpha Version  CC0';
export const TITLE_SUB_COLOR = 7;      // light gray
export const TITLE_SUB_MS = 20;        // subtitle types in at this many ms per char
export const TITLE_DECODE_MS = 1200;    // intro: noise resolves into the title left to right
export const TITLE_SHIMMER = [9, 11, 15, 11, 9, 1, 13, 5];  // color wave across the letters
export const TITLE_SHIMMER_SPEED = 6;   // wave steps per second
export const TITLE_GRAVITY = 40;        // rows/s^2 for the falling particles
export const TITLE_LIFE_S = 1.4;        // average particle life
export const TITLE_DECAY = [['#', 15], ['*', 11], ['+', 9], ['.', 8]];  // particle look over its life
export const SOUND_VOL = 0.5;           // master volume
export const BLIP_VOL = 0.4;            // incoming messages at max zoom, relative to the send sound (soft triangle wave)
export const BLIP_FAR = 0.1;            // ...scaled down to this fraction at min zoom
export const BLIP_NEAR = 0.4;           // only messages this close to you blip (1 = screen edge, like MSG_FADE)
export const STEP_VOL = 0.12;           // arrow-key tick, relative to the send sound
export const WHOOSH_VOL = 0.15;         // turning the planet
export const WHOOSH_SMOOTH_S = 0.3;     // whoosh volume/pitch follow the turn speed this slowly
export const WHOOSH_HZ = [200, 900];    // lowpass cutoff at rest .. full speed
export const WHOOSH_FULL_SPEED = 3;     // rad/s of turning that gives the full whoosh
export const ZOOM_BEEP_MS = 70;         // min gap between zoom beeps
export const MUSIC_VOL = 0.5;           // intro music, relative to master
export const MUSIC_BAR_S = 2.4;         // one chord per bar
export const MUSIC_LOOPS = 1;           // 4 bars per loop, then a closing chord
export const LONG_FRAME_MS = 60;      // telemetry: log renders slower than this
export const LOG_URL = '/log';
export const FEEDBACK_URL = 'https://forms.gle/HhmiZXJZiunUFKLJ9';
export const HINT = ['click anywhere to say hi', 'type and press enter to say hi'];  // bottom center until your first message: [no pin, pin]
export const HINT_TOUCH = 'tap anywhere to say hi';  // phones, before the first tap
export const TAP_SLOP_PX = 10;           // a touch that moves less than this is a tap (opens the keyboard), more is a drag
export const HINT_COLOR = 7;              // light gray
export const CHAT_LINES = 6;             // global chat, bottom right, always shown: last messages from everyone (relay sends its recent ones on connect), newest at the bottom
export const CHAT_W = 40;                 // cols; longer messages are cut
export const CHAT_TITLE = ['GLOBAL CHAT', 8];  // text, color: header line, always shown
export const CHAT_EMPTY = 'no messages yet';
export const CHAT_COLOR = 7;              // light gray (own lines in ME_COLOR)
export const GITHUB_URL = 'https://github.com/franciscocarloserra';
