# Writes data/curses.js. A curse may match inside other words only if it never shows up inside a real word of the
# system Spanish/English dictionaries (so "therapist" or "ridiculo" pass); otherwise it only matches as a whole word.
# Normalization must stay in sync with norm() in js/filter.js.
import json, re, unicodedata

MIN_INFIX = 4
SOURCE = '../curse-chat/data/words.json'  # github.com/awdev1/better-profane-words
MIN_INTENSITY = 2
DICTS = ['/usr/share/dict/spanish', '/usr/share/dict/american-english']
SPANISH = """puta puto putas putos putita mierda concha conchudo conchuda pija pete boludo boluda pelotudo pelotuda
culiao culiado culo joder jodete gilipollas cabron cabrona pendejo pendeja verga chinga chingada mamaguevo
maricon marica trolo hdp ctm mogolico""".split()
# threats and calls to self-harm, always blocked (phrases match as whole words)
AGGRESSIVE = [l.strip() for l in '''
te voy a matar|voy a matarte|te mato|te voy a buscar|se donde vivis|se donde vives|matate|suicidate|muerete|ojala te mueras
ojala te muera|ojala se muera|ojala se mueran|te voy a violar|te violo|te rompo la cara|te cago a trompadas|te cago a palos
te voy a cagar a trompadas|te voy a romper|tirate de un puente|cortate las venas|ahorcate|pegate un tiro|hay que matarlos
kill yourself|kill urself|kys|go die|hope you die|i will kill you|ill kill you|gonna kill you|i will find you|rape you
neck yourself|hang yourself|shoot yourself|slit your wrists|i know where you live|you should die|die in a fire
'''.replace('\n', '|').split('|') if l.strip()]
# English list entries that are also dictionary words are dropped (abed, wily, chugs...), except these real curses
KEEP = 'fuck fucker fucking shit shits bitch bitches cunt dick cock cocks pussy asshole bastard bastards whore slut fag faggot nigger nigga niggas twat wanker motherfucker bullshit jackass prick pricks'.split()
LEET = str.maketrans('013457@$', 'oieasta' + 's')

def norm(s):
    s = ''.join(c for c in unicodedata.normalize('NFD', s) if unicodedata.category(c) != 'Mn').lower().translate(LEET)
    return re.sub(r'(.)\1+', r'\1', re.sub(r'[^a-z]+', ' ', s)).strip()

words = {norm(w) for d in DICTS for w in open(d) if w.strip() and "'" not in w and not w[0].isupper()}
src = {norm(e['word']) for e in json.load(open(SOURCE)) if e['intensity'] >= MIN_INTENSITY}
keep = {norm(w) for w in KEEP}
src = {w for w in src if w and (w not in words or w in keep)}
curses = src | {norm(w) for w in SPANISH + AGGRESSIVE}
words -= curses
blob = '\n'.join(words)
infix = sorted(w for w in curses if ' ' not in w and len(w) >= MIN_INFIX and w not in blob)
whole = sorted(curses - set(infix))
with open('data/curses.js', 'w') as f:
    f.write('// Generated by make_curses.py. Normalized curse words: INFIX match anywhere, WHOLE only as whole words.\n')
    f.write(f'export const INFIX = {json.dumps(infix)};\nexport const WHOLE = {json.dumps(whole)};\n')
print(len(infix), 'infix', len(whole), 'whole')
